// ganglia-webui/src/components/Inspector.tsx
import React, { useMemo, useRef, useEffect } from 'react'
import { useSystemStore } from '../stores/system'
import { useLogStore } from '../stores/log'
import { eventBusService } from '../services/eventbus'
import { useVirtualizer } from '@tanstack/react-virtual'
import Prism from 'prismjs'
import 'prismjs/themes/prism-tomorrow.css'
import 'prismjs/components/prism-java'
import 'prismjs/components/prism-javascript'
import 'prismjs/components/prism-typescript'
import 'prismjs/components/prism-bash'
import 'prismjs/components/prism-python'
import 'prismjs/components/prism-diff'
import 'prismjs/components/prism-json'
import { cn } from '../lib/utils'

const Inspector: React.FC = () => {
  const systemStore = useSystemStore()
  const logStore = useLogStore()

  const parentRef = useRef<HTMLDivElement>(null)

  const ttyLines = useMemo(() => {
    if (!systemStore.inspectorToolCallId) return []
    const allLines = logStore.activeToolCalls[systemStore.inspectorToolCallId] || []

    if (!systemStore.terminalSearchQuery) return allLines

    try {
      const regex = new RegExp(systemStore.terminalSearchQuery, 'i')
      return allLines.filter((line) => regex.test(line))
    } catch (e) {
      return allLines.filter((line) => line.toLowerCase().includes(systemStore.terminalSearchQuery.toLowerCase()))
    }
  }, [systemStore.inspectorToolCallId, logStore.activeToolCalls, systemStore.terminalSearchQuery])

  const rowVirtualizer = useVirtualizer({
    count: ttyLines.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 20,
    overscan: 10,
  })

  useEffect(() => {
    if (parentRef.current && systemStore.inspectorMode === 'TERMINAL') {
      const { scrollTop, scrollHeight, clientHeight } = parentRef.current
      const isAtBottom = scrollHeight - scrollTop - clientHeight < 50
      if (isAtBottom && ttyLines.length > 0) {
        rowVirtualizer.scrollToIndex(ttyLines.length - 1)
      }
    }
  }, [ttyLines.length, systemStore.inspectorMode, rowVirtualizer])

  useEffect(() => {
    if (systemStore.inspectFile) {
      eventBusService.send('READ_FILE', { path: systemStore.inspectFile })
    }
  }, [systemStore.inspectFile])

  const currentFile = useMemo(() => {
    if (!systemStore.inspectFile) return null
    return logStore.fileCache[systemStore.inspectFile] || null
  }, [systemStore.inspectFile, logStore.fileCache])

  const highlightedCode = useMemo(() => {
    if (systemStore.inspectorMode === 'CODE' && currentFile) {
      const lang = currentFile.language || 'text'
      const grammar = Prism.languages[lang] || Prism.languages.text
      return Prism.highlight(currentFile.content, grammar, lang)
    }
    return ''
  }, [systemStore.inspectorMode, currentFile])

  const highlightedDiff = useMemo(() => {
    if (systemStore.inspectorMode === 'DIFF' && systemStore.inspectDiff) {
      return Prism.highlight(systemStore.inspectDiff, Prism.languages.diff, 'diff')
    }
    return ''
  }, [systemStore.inspectorMode, systemStore.inspectDiff])

  const copyCode = () => {
    if (systemStore.inspectorMode === 'CODE' && currentFile) {
      navigator.clipboard.writeText(currentFile.content)
    } else if (systemStore.inspectorMode === 'DIFF' && systemStore.inspectDiff) {
      navigator.clipboard.writeText(systemStore.inspectDiff)
    }
  }

  if (!systemStore.isInspectorOpen) return null

  return (
    <aside className="w-[700px] bg-slate-900 border-l border-slate-800 flex flex-col h-full shadow-2xl animate-in slide-in-from-right duration-300 z-20">
      <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-950 shrink-0">
        <div className="flex flex-col flex-1 min-w-0">
          <div className="flex items-center gap-3 mb-1">
            <h3 className="text-xs font-semibold text-slate-200 uppercase tracking-widest">Inspector</h3>
            <div className="flex bg-slate-900 rounded p-0.5 border border-slate-800">
              {(['TERMINAL', 'CODE', 'DIFF'] as const).map((mode) => (
                <button
                  key={mode}
                  onClick={() => systemStore.toggleInspector(systemStore.inspectorToolCallId, mode)}
                  className={cn(
                    'px-2 py-0.5 text-[10px] rounded transition-colors',
                    systemStore.inspectorMode === mode ? 'bg-slate-700 text-white' : 'text-slate-500 hover:text-slate-300'
                  )}
                >
                  {mode === 'TERMINAL' ? 'Terminal' : mode === 'CODE' ? 'Code' : 'Diff'}
                </button>
              ))}
            </div>
          </div>
          <span className="text-[10px] font-mono text-slate-500 truncate block">
            {systemStore.inspectorMode === 'TERMINAL' && `Target: ${systemStore.inspectorToolCallId}`}
            {systemStore.inspectorMode === 'CODE' && `File: ${systemStore.inspectFile}`}
            {systemStore.inspectorMode === 'DIFF' && 'Diff Review'}
          </span>
        </div>

        <div className="flex items-center gap-2">
          {systemStore.inspectorMode === 'CODE' && systemStore.inspectFile && (
            <button
              onClick={() => systemStore.addContextToPrompt(systemStore.inspectFile!)}
              className="text-slate-500 hover:text-emerald-400 transition-colors p-1"
              title="Add to context"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 5v14M5 12h14" />
              </svg>
            </button>
          )}
          {((systemStore.inspectorMode === 'CODE' && currentFile) || (systemStore.inspectorMode === 'DIFF' && systemStore.inspectDiff)) && (
            <button onClick={copyCode} className="text-slate-500 hover:text-emerald-400 transition-colors p-1" title="Copy to clipboard">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
              </svg>
            </button>
          )}
          <button onClick={() => systemStore.closeInspector()} className="text-slate-500 hover:text-white transition-colors p-1">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </button>
        </div>
      </div>

      <div className="flex-1 relative bg-black overflow-hidden flex flex-col">
        {systemStore.inspectorMode === 'TERMINAL' && (
          <div className="flex-1 flex flex-col min-h-0">
            <div className="px-4 py-2 border-b border-slate-800 bg-slate-900/50 flex items-center gap-3 shrink-0">
              <div className="relative flex-1">
                <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500 text-[10px]">🔍</span>
                <input
                  value={systemStore.terminalSearchQuery}
                  onChange={(e) => useSystemStore.setState({ terminalSearchQuery: e.target.value })}
                  type="text"
                  placeholder="Filter logs (regex supported)..."
                  className="w-full bg-black border border-slate-800 rounded px-8 py-1 text-[11px] text-slate-300 focus:outline-none focus:border-emerald-500/50 placeholder:text-slate-600 transition-all"
                />
                {systemStore.terminalSearchQuery && (
                  <button
                    onClick={() => useSystemStore.setState({ terminalSearchQuery: '' })}
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 text-[10px]"
                  >
                    ✕
                  </button>
                )}
              </div>
              <div className="text-[10px] text-slate-500 font-mono whitespace-nowrap">{ttyLines.length} lines</div>
            </div>

            <div ref={parentRef} className="flex-1 w-full overflow-auto p-4 font-mono text-[11px] leading-tight text-slate-300">
              {ttyLines.length === 0 ? (
                <div className="opacity-30 italic p-4 text-center">
                  {systemStore.terminalSearchQuery ? 'No lines matching search query.' : 'No output recorded for this tool call.'}
                </div>
              ) : (
                <div
                  style={{
                    height: `${rowVirtualizer.getTotalSize()}px`,
                    width: '100%',
                    position: 'relative',
                  }}
                >
                  {rowVirtualizer.getVirtualItems().map((virtualRow) => (
                    <div
                      key={virtualRow.index}
                      style={{
                        position: 'absolute',
                        top: 0,
                        left: 0,
                        width: '100%',
                        height: `${virtualRow.size}px`,
                        transform: `translateY(${virtualRow.start}px)`,
                      }}
                      className="whitespace-pre break-all border-b border-slate-900/30 py-0.5 px-1 hover:bg-slate-900/50"
                    >
                      {ttyLines[virtualRow.index]}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {systemStore.inspectorMode === 'CODE' && (
          <div className="flex-1 flex flex-col min-h-0 bg-[#1d1f21]">
            {!systemStore.inspectFile ? (
              <div className="flex-1 flex flex-col items-center justify-center p-8 text-center">
                <div className="text-3xl mb-4 opacity-20">📄</div>
                <h4 className="text-sm font-medium text-slate-400">No file selected</h4>
                <p className="text-[10px] text-slate-600 mt-2 max-w-xs leading-relaxed">
                  Select a file path from the conversation or tool execution to inspect its content.
                </p>
              </div>
            ) : !currentFile ? (
              <div className="flex-1 flex items-center justify-center">
                <div className="flex items-center gap-2 text-slate-500">
                  <span className="w-4 h-4 border-2 border-slate-500 border-t-transparent rounded-full animate-spin"></span>
                  <span className="text-xs">Reading file...</span>
                </div>
              </div>
            ) : (
              <div className="flex-1 overflow-auto p-4">
                <pre className="!bg-transparent !m-0 !p-0">
                  <code dangerouslySetInnerHTML={{ __html: highlightedCode }} />
                </pre>
              </div>
            )}
          </div>
        )}

        {systemStore.inspectorMode === 'DIFF' && (
          <div className="flex-1 flex flex-col min-h-0 bg-[#1d1f21]">
            {!systemStore.inspectDiff ? (
              <div className="flex-1 flex flex-col items-center justify-center p-8 text-center">
                <div className="text-3xl mb-4 opacity-20">📝</div>
                <h4 className="text-sm font-medium text-slate-400">No diff available</h4>
              </div>
            ) : (
              <div className="flex-1 overflow-auto p-4">
                <pre className="!bg-transparent !m-0 !p-0 text-xs">
                  <code dangerouslySetInnerHTML={{ __html: highlightedDiff }} />
                </pre>
              </div>
            )}
          </div>
        )}
      </div>
    </aside>
  )
}

export default Inspector

// ganglia-webui/src/components/Inspector.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted, nextTick } from 'vue'
import { useSystemStore } from '../stores/system'
import { useLogStore } from '../stores/log'
import { eventBusService } from '../services/eventbus'
import { useVirtualizer } from '@tanstack/vue-virtual'
import { createHighlighter } from 'shiki'

const systemStore = useSystemStore()
const logStore = useLogStore()

const parentRef = ref<HTMLElement | null>(null)
const highlighter = ref<any>(null)
const highlightedCode = ref('')
const highlightedDiff = ref('')

onMounted(async () => {
  highlighter.value = await createHighlighter({
    themes: ['github-dark'],
    langs: ['java', 'javascript', 'typescript', 'xml', 'json', 'bash', 'markdown', 'python', 'yaml', 'diff']
  })
})

const ttyLines = computed(() => {
  if (!systemStore.inspectorToolCallId) return []
  const allLines = logStore.activeToolCalls[systemStore.inspectorToolCallId] || []
  
  if (!systemStore.terminalSearchQuery) return allLines
  
  try {
    const regex = new RegExp(systemStore.terminalSearchQuery, 'i')
    return allLines.filter(line => regex.test(line))
  } catch (e) {
    // If invalid regex, just return all lines or handle as plain string
    return allLines.filter(line => line.toLowerCase().includes(systemStore.terminalSearchQuery.toLowerCase()))
  }
})

const rowVirtualizer = useVirtualizer(
  computed(() => ({
    count: ttyLines.value.length,
    getScrollElement: () => parentRef.value,
    estimateSize: () => 20,
    overscan: 10,
  }))
)

// Auto-scroll when new lines arrive if we're near the bottom
watch(() => ttyLines.value.length, (newCount) => {
  if (parentRef.value && systemStore.inspectorMode === 'TERMINAL') {
    const { scrollTop, scrollHeight, clientHeight } = parentRef.value
    const isAtBottom = scrollHeight - scrollTop - clientHeight < 50
    if (isAtBottom) {
      nextTick(() => {
        rowVirtualizer.value.scrollToIndex(newCount - 1)
      })
    }
  }
})

// Code inspection logic
watch(() => systemStore.inspectFile, (newPath) => {
  if (newPath) {
    eventBusService.send('READ_FILE', { path: newPath })
  }
})

watch([() => logStore.fileCache, () => systemStore.inspectFile, highlighter], () => {
  if (systemStore.inspectFile && highlighter.value) {
    const file = logStore.fileCache[systemStore.inspectFile]
    if (file) {
      highlightedCode.value = highlighter.value.codeToHtml(file.content, {
        lang: file.language || 'text',
        theme: 'github-dark'
      })
    }
  }
}, { deep: true })

// Diff inspection logic
watch([() => systemStore.inspectDiff, highlighter], () => {
  if (systemStore.inspectDiff && highlighter.value) {
    highlightedDiff.value = highlighter.value.codeToHtml(systemStore.inspectDiff, {
      lang: 'diff',
      theme: 'github-dark'
    })
  }
}, { immediate: true })

const currentFile = computed(() => {
  if (!systemStore.inspectFile) return null
  return logStore.fileCache[systemStore.inspectFile] || null
})

const copyCode = () => {
  if (systemStore.inspectorMode === 'CODE' && currentFile.value) {
    navigator.clipboard.writeText(currentFile.value.content)
  } else if (systemStore.inspectorMode === 'DIFF' && systemStore.inspectDiff) {
    navigator.clipboard.writeText(systemStore.inspectDiff)
  }
}
</script>

<template>
  <aside 
    v-if="systemStore.isInspectorOpen"
    class="w-[700px] bg-slate-900 border-l border-slate-800 flex flex-col h-full shadow-2xl animate-in slide-in-from-right duration-300 z-20"
  >
    <!-- Header -->
    <div class="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-950">
      <div class="flex flex-col flex-1 min-w-0">
        <div class="flex items-center gap-3 mb-1">
          <h3 class="text-xs font-semibold text-slate-200 uppercase tracking-widest">Inspector</h3>
          <div class="flex bg-slate-900 rounded p-0.5 border border-slate-800">
            <button 
              @click="systemStore.inspectorMode = 'TERMINAL'"
              class="px-2 py-0.5 text-[10px] rounded transition-colors"
              :class="systemStore.inspectorMode === 'TERMINAL' ? 'bg-slate-700 text-white' : 'text-slate-500 hover:text-slate-300'"
            >
              Terminal
            </button>
            <button 
              @click="systemStore.inspectorMode = 'CODE'"
              class="px-2 py-0.5 text-[10px] rounded transition-colors"
              :class="systemStore.inspectorMode === 'CODE' ? 'bg-slate-700 text-white' : 'text-slate-500 hover:text-slate-300'"
            >
              Code
            </button>
            <button 
              @click="systemStore.inspectorMode = 'DIFF'"
              class="px-2 py-0.5 text-[10px] rounded transition-colors"
              :class="systemStore.inspectorMode === 'DIFF' ? 'bg-slate-700 text-white' : 'text-slate-500 hover:text-slate-300'"
            >
              Diff
            </button>
          </div>
        </div>
        <span class="text-[10px] font-mono text-slate-500 truncate block">
          <template v-if="systemStore.inspectorMode === 'TERMINAL'">Target: {{ systemStore.inspectorToolCallId }}</template>
          <template v-else-if="systemStore.inspectorMode === 'CODE'">File: {{ systemStore.inspectFile }}</template>
          <template v-else-if="systemStore.inspectorMode === 'DIFF'">Diff Review</template>
        </span>
      </div>
      
      <div class="flex items-center gap-2">
        <button 
          v-if="systemStore.inspectorMode === 'CODE' && systemStore.inspectFile"
          @click="systemStore.addContextToPrompt(systemStore.inspectFile!)"
          class="text-slate-500 hover:text-emerald-400 transition-colors p-1"
          title="Add to context"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg>
        </button>
        <button 
          v-if="(systemStore.inspectorMode === 'CODE' && currentFile) || (systemStore.inspectorMode === 'DIFF' && systemStore.inspectDiff)"
          @click="copyCode"
          class="text-slate-500 hover:text-emerald-400 transition-colors p-1"
          title="Copy to clipboard"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
        </button>
        <button 
          @click="systemStore.closeInspector()"
          class="text-slate-500 hover:text-white transition-colors p-1"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
        </button>
      </div>
    </div>
    
    <!-- Content Area -->
    <div class="flex-1 relative bg-black overflow-hidden flex flex-col">
      
      <!-- Terminal View (Virtual List) -->
      <div 
        v-if="systemStore.inspectorMode === 'TERMINAL'"
        class="flex-1 flex flex-col min-h-0"
      >
        <!-- Search Bar -->
        <div class="px-4 py-2 border-b border-slate-800 bg-slate-900/50 flex items-center gap-3">
          <div class="relative flex-1">
            <span class="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500 text-[10px]">🔍</span>
            <input 
              v-model="systemStore.terminalSearchQuery"
              type="text"
              placeholder="Filter logs (regex supported)..."
              class="w-full bg-black border border-slate-800 rounded px-8 py-1 text-[11px] text-slate-300 focus:outline-none focus:border-emerald-500/50 placeholder:text-slate-600 transition-all"
            />
            <button 
              v-if="systemStore.terminalSearchQuery"
              @click="systemStore.terminalSearchQuery = ''"
              class="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 text-[10px]"
            >
              ✕
            </button>
          </div>
          <div class="text-[10px] text-slate-500 font-mono whitespace-nowrap">
            {{ ttyLines.length }} lines
          </div>
        </div>

        <div 
          ref="parentRef"
          class="flex-1 w-full overflow-auto p-4 font-mono text-[11px] leading-tight text-slate-300"
        >
          <div v-if="ttyLines.length === 0" class="opacity-30 italic p-4 text-center">
            {{ systemStore.terminalSearchQuery ? 'No lines matching search query.' : 'No output recorded for this tool call.' }}
          </div>
          
          <div
            v-else
            :style="{
              height: `${rowVirtualizer.getTotalSize()}px`,
              width: '100%',
              position: 'relative',
            }"
          >
            <div
              v-for="virtualRow in rowVirtualizer.getVirtualItems()"
              :key="virtualRow.index"
              :style="{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: `${virtualRow.size}px`,
                transform: `translateY(${virtualRow.start}px)`,
              }"
              class="whitespace-pre break-all border-b border-slate-900/30 py-0.5 px-1 hover:bg-slate-900/50"
            >
              {{ ttyLines[virtualRow.index] }}
            </div>
          </div>
        </div>
      </div>

      <!-- Code View -->
      <div v-else-if="systemStore.inspectorMode === 'CODE'" class="flex-1 flex flex-col min-h-0">
        <div v-if="!systemStore.inspectFile" class="flex-1 flex flex-col items-center justify-center p-8 text-center">
          <div class="text-3xl mb-4 opacity-20">📄</div>
          <h4 class="text-sm font-medium text-slate-400">No file selected</h4>
          <p class="text-[10px] text-slate-600 mt-2 max-w-xs leading-relaxed">
            Select a file path from the conversation or tool execution to inspect its content.
          </p>
        </div>
        <div v-else-if="!currentFile" class="flex-1 flex items-center justify-center">
          <div class="flex items-center gap-2 text-slate-500">
            <span class="w-4 h-4 border-2 border-slate-500 border-t-transparent rounded-full animate-spin"></span>
            <span class="text-xs">Reading file...</span>
          </div>
        </div>
        <div v-else class="flex-1 overflow-auto bg-[#0d1117]">
          <div v-html="highlightedCode" class="shiki-container"></div>
        </div>
      </div>
      
      <!-- Diff View -->
      <div v-else-if="systemStore.inspectorMode === 'DIFF'" class="flex-1 flex flex-col min-h-0">
        <div v-if="!systemStore.inspectDiff" class="flex-1 flex flex-col items-center justify-center p-8 text-center">
          <div class="text-3xl mb-4 opacity-20">📝</div>
          <h4 class="text-sm font-medium text-slate-400">No diff available</h4>
        </div>
        <div v-else class="flex-1 overflow-auto bg-[#0d1117]">
          <div v-html="highlightedDiff" class="shiki-container"></div>
        </div>
      </div>

    </div>
  </aside>
</template>

<style scoped>
.font-mono {
  font-family: 'JetBrains Mono', 'Fira Code', 'Ubuntu Mono', monospace;
}

/* Custom scrollbar */
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-thumb {
  background: #334155;
}
::-webkit-scrollbar-track {
  background: #020617;
}

.shiki-container :deep(pre) {
  margin: 0;
  padding: 1.5rem;
  background-color: transparent !important;
  font-size: 12px;
  line-height: 1.6;
  tab-size: 4;
}

.shiki-container :deep(code) {
  font-family: inherit;
}
</style>
