// ganglia-webui/src/components/ThoughtCard.tsx
import React, { useState } from 'react'
import { cn } from '../lib/utils'

interface ThoughtCardProps {
  content: string
  initiallyExpanded?: boolean
}

const ThoughtCard: React.FC<ThoughtCardProps> = ({ content, initiallyExpanded = false }) => {
  const [isExpanded, setIsExpanded] = useState(initiallyExpanded)

  return (
    <div className="border-l-2 border-slate-700 pl-4 py-1 my-2">
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="text-[10px] uppercase tracking-widest text-slate-500 hover:text-slate-300 flex items-center gap-2 transition-colors"
      >
        <span className={cn('transition-transform inline-block', isExpanded && 'rotate-90')}>▶</span>
        Thought Process
      </button>

      {isExpanded && (
        <div className="mt-2 text-sm text-slate-400 italic leading-relaxed animate-in fade-in slide-in-from-top-1 duration-200">
          {content}
        </div>
      )}
    </div>
  )
}

export default ThoughtCard

// ganglia-webui/src/components/ThoughtCard.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  content: string
  initiallyExpanded?: boolean
}>()

const isExpanded = ref(props.initiallyExpanded || false)
</script>

<template>
  <div class="border-l-2 border-slate-700 pl-4 py-1 my-2">
    <button 
      @click="isExpanded = !isExpanded"
      class="text-[10px] uppercase tracking-widest text-slate-500 hover:text-slate-300 flex items-center gap-2 transition-colors"
    >
      <span :class="{ 'rotate-90': isExpanded }" class="transition-transform inline-block">▶</span>
      Thought Process
    </button>
    
    <div v-if="isExpanded" class="mt-2 text-sm text-slate-400 italic leading-relaxed animate-in fade-in slide-in-from-top-1 duration-200">
      {{ content }}
    </div>
  </div>
</template>
